project:
  type: website
  output-dir: docs

resources: 
  - CNAME

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "Eisenhofer Photography"
  site-url: https://eisenra.github.io/the_raph_round-up/
  description: "Eisenhofer Photography"
  navbar:
    left:
      - About.qmd
      - Photography.qmd
      - text: "Blog"
        href: Blog.qmd
      - text: "AI statement"
        href: ai_statement.qmd

    right:
      - icon: camera
        href: https://pixelfed.social/Eisen_Raph
      - icon: mastodon
        href: https://genomic.social/@EisenRa
      - icon: github
        href: https://github.com/EisenRa
      - icon: rss
        href: index.xml

# https://quarto.org/docs/reference/projects/websites.html#hypothesis
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
    image-lazy-loading: TRUE
    css: styles.css
    include-in-header:
      - text: |
          <script defer src="https://cloud.umami.is/script.js" data-website-id="e2a67f0d-57bf-4127-a586-dd84b56b758f"></script>

    
execute:
  freeze: auto
  
editor: visual

